---
# tasks file for openjdk
# Author: Arthur Niu
#

- name: install JDK which is defined in vars/mail.yml
  apt:
    name: "{{ target_jdk }}"
    state: latest

- name:
  shell: java -version
  register: java_version

- name:
  debug:
    msg: "{{ java_version }}"

