---
# tasks file for nginx
# # Author: Arthur Niu
#
- name: load vars from globe role
  include_vars: 
    file: "{{ playbook_dir }}/roles/global/vars/main.yml"

- name: install nginx
  apt:
    name: nginx-full
    state: latest
  
- name: remove default nginx link
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: copy reverse-proxy.conf to nginx server
  template:
    src: reverse-proxy.conf
    dest: /etc/nginx/sites-available
    mode: 0644

- name: create link to reverse-proxy.conf
  file:
    src: /etc/nginx/sites-available/reverse-proxy.conf
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    state: link

- name: enable nginx
  service:
    name: nginx
    enabled: yes  

- name: start nginx
  service:
    name: nginx
    state: started
  notify: Check HTTP Service

#- name: Check HTTP Service
  #  uri:
          #    url: http://{{ ansible_default_ipv4.address }}
    #    status_code: 200

- include: sslConfig.yml
