#
# Author: Arthur Niu
#
#
---
-
  hosts: all
  become: yes

  roles:
    - global

- 
  hosts: sonarqubedatabase
  become: yes

  roles: 
    - postgresql


-
  hosts: sonarqubes
  become: yes

  roles:
    - sonarqube
