#
# Author: Arthur Niu
#
#
---
# Run tasks on local only
# Configure the prerequisited for local
-
  hosts: localhost

  connection: local
  roles:
    - local

# Run tasks on all targets
# Prepare the prerequisites for all targets
-
  hosts: all
  become: yes

  roles:
    - global

# Run tasks for sonarqube database
- 
  hosts: sonarqubedatabase
  become: yes

  roles: 
    - postgresql

# Run tasks for sonarqube 
-
  hosts: sonarqubes
  become: yes

  roles:
    - sonarqube
